[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 10

[[main]]
  name = "About Scicloj"
  weight = 21
  identifier = "about"
  url = "/docs/community/about/"
  parent = "Community"

[[main]]
  name = "Getting involved"
  weight = 22
  identifier = "getting_involved"
  url = "/docs/community/getting_involved/"
  parent = "Community"

[[main]]
  name = "Study & dev groups"
  weight = 23
  identifier = "groups"
  url = "/docs/community/groups/"
  parent = "Community"

[[main]]
  name = "Chat Streams"
  weight = 24
  identifier = "chat"
  url = "/docs/community/chat/"
  parent = "Community"

[[main]]
  name = "Contact"
  weight = 25
  identifier = "contact"
  url = "/docs/community/contact/"
  parent = "Community"

[[main]]
  name = "Tools & libraries"
  weight = 31
  identifier = "libs"
  url = "/docs/resources/libs"
  parent = "Resources"

[[main]]
  name = "Reading"
  weight = 32
  identifier = "reading"
  url = "/docs/resources/reading"
  parent = "Resources"

[[main]]
  name = "Video"
  weight = 33
  identifier = "video"
  url = "/docs/resources/video"
  parent = "Resources"

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/scicloj"
  post = "v0.1.0"
  weight = 10

[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/scicloj"
  weight = 20

# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10









# [[main]]
#   name = "Community"
#   weight = 30
#   identifier = "community"
#   url = "/community"

# [[main]]
#   name = "Getting involved"
#   weight = 31
#   identifier = "getting-involved"
#   url = "/community/getting-involved"
#   parent = "community"

# [[main]]
#   name = "Study & dev groups"
#   weight = 32
#   identifier = "groups"
#   url = "/community/groups"
#   parent = "community"

# [[main]]
#   name = "Code of Conduct"
#   weight = 33
#   identifier = "coc"
#   url = "/community/coc"
#   parent = "community"

# [[main]]
#   name = "Chat streams"
#   weight = 33
#   identifier = "chat"
#   url = "/community/chat"
#   parent = "community"

# [[main]]
#   name = "About"
#   weight = 34
#   identifier = "about"
#   url = "/community/about"
#   parent = "community"

# [[main]]
#   name = "Contact"
#   weight = 35
#   identifier = "contact"
#   url = "/community/contact"
#   parent = "community"

# [[main]]
#   name = "Resources"
#   weight = 40
#   identifier = "resources"
#   url = "/resources"

# [[main]]
#   name = "Tools & libraries"
#   weight = 41
#   identifier = "libs"
#   url = "/resources/libs"
#   parent = "resources"

# [[main]]
#   name = "Talks & workshops"
#   weight = 42
#   identifier = "videos"
#   url = "/resources/videos"
#   parent = "resources"

# [[main]]
#   name = "Reading"
#   weight = 43
#   identifier = "reading"
#   url = "/resources/reading"
#   parent = "resources"

